site_name: Gemeentelijk Gegevensmodel (GGM)
site_description: Informatiemodel van alle gemeentelijke taakvelden 
site_author: Arjen Brienen
date: 2019-05-12
repo_url: https://github.com/brienen/Gemeentelijk-Gegevensmodel/
google_analytics: ['UA-109371818-2', 'brienen.github.io/Gemeentelijk-Gegevensmodel/']
nav:
 - Home: index.md
 - Installatie: installatie.md
 - Opbouw (Under Construction): 
    - 'Griffie': domeinen/griffie.md 
    - 'Burgerzaken': domeinen/burgerzaken.md 
    - 'Onderwijs': domeinen/onderwijs.md 
    - 'Leerplicht en leerlingenvervoer': domeinen/leerplicht.md 
    - 'Ruimte': 
        - 'Ruimte Algemeen': domeinen/ruimteAlgemeen.md
        - 'Afval': domeinen/afval.md
    - 'Bestuur en Ondersteuning':
        - 'HR': domeinen/hr.md
        - 'Gemeentelijk Vastgoed': domeinen/vastgoed.md
        - 'Financiën': domeinen/financien.md
        - 'Inkoop': domeinen/inkoop.md
        - 'ICT': domeinen/ict.md
    - 'Sport, Cultuur en Recreatie':
        - 'Erfgoed: Archeologie': domeinen/archeologie.md
        - 'Erfgoed: Monumenten': domeinen/monumenten.md
        - 'Erfgoed: Archief': domeinen/archief.md
        - 'Erfgoed: Museum': domeinen/museum.md
        - 'Erfgoed: Generieke objecttypen': domeinen/erfgoedgeneriek.md
    - 'Vergunningverlening Toezicht en Handhaving': domeinen/vth.md 
 # - Gebruik: gebruik.md
 - Totstandkoming:
    - 'Uitleg Werkwijze': totstandkoming.md
    - 'Voorbeeld: Gemeentelijke Monumenten': monumenten.md
 - Generatie databaseschema's: generatie.md
 - Overige: 
    - Over het GGM: about.md
    - Licentie: https://github.com/brienen/Gemeentelijk-Gegevensmodel/blob/master/LICENSE 
    - Documentatie aanpassen: documentatie.md
theme: 
    name: 'material'
    language: 'nl'
    palette:
        primary: 'blue'
        accent: 'blue'
markdown_extensions:
  - admonition