name: UML to JSON Schema Converter

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/schemas/**'
      - '**/*.md'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version folder to process (e.g., v2.1.0)'
        required: false
        default: ''

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install xmltodict pyyaml json-schema-generator chardet tqdm

      - name: Run conversion script
        run: python .github/scripts/convert_uml_to_schema.py ${{ inputs.version }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add v*/schemas/
          git commit -m "Update JSON Schemas and OpenAPI spec" || echo "No changes to commit"
          git push 